# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SSH@0
  inputs:
    sshEndpoint: 'Digital Ocean SSH Connection'
    runOptions: 'commands'
    commands: cd ~/code/disney-plus-clone/ &&  git pull 2> git_error.log && echo "Git pull completed successfully";
    readyTimeout: '20000'
  displayName: 'Git pull'
- task: SSH@0
  inputs:
    sshEndpoint: 'Digital Ocean SSH Connection'
    runOptions: 'commands'
    commands: cd ~/code/disney-plus-clone/ &&  npm i 2> npm_install_errors.log && echo "Installed dependencies successfully";
    readyTimeout: '20000'
  displayName: 'Installing Dependencies'

- task: SSH@0
  inputs:
    sshEndpoint: 'Digital Ocean SSH Connection'
    runOptions: 'commands'
    commands: cd ~/code/disney-plus-clone/ && npm run build > /dev/null 2> npm_run_build_errors.log && echo "Built files successfully";
    readyTimeout: '20000'
  displayName: 'Building Files'
- task: SSH@0
  inputs:
    sshEndpoint: 'Digital Ocean SSH Connection'
    runOptions: 'commands'
    commands: 'pm2 restart MovieGenie'
    readyTimeout: '20000'
  displayName: 'Restart pm2'
